context:
  expressions:
    activity_conversation:
      - let's (have a) chat
    activity_scavenger_hunt:
      - (let's) play hide and seek
      - (let's) (go on a) scavenger hunt
    activity_sleep:
      - go to sleep (please)
    activity_move:
      - let's play catch
    activity_play_music:
      - play a tune
    activity_story:
      - It's story time
      - Tell me a story
    activity_poem:
      - Let's make a poem
      - Tell me a poem
    activity_discovery:
      - Let's learn together
      - Let's play discovery
    activity_bedtime:
      - Goodnight
      - Night light
      - It's time for bed
      - It's bedtime
    activity_call:
      - "[call, phone] $contact:contact please"
      - Please [call, phone] $contact:contact
    command_custom:
      - custom command $pv.SingleDigitInteger:index
    command_volume:
      - volume $volume:command
      - volume $pv.SingleDigitInteger:level
  slots:
    contact:
      - mom
      - dad
      - Ash
      - Lucy
      - Tom
    volume:
      - on
      - off
      - down
      - up
  macros: {}
